backend:
  name: auth0
  repo: renegade620/my-girls-rights-blog
  branch: main
  auth0:
    domain: dev-snve1s0vvuty0tjn.us.auth0.com
    client_id: BCj0rvJot1EPV65nUFY1KBXVYQyUW0zp

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://my-girls-rights.netlify.app"

collections:
  - name: "posts"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}" # Optional, adjust to your routing
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: false, hint: "Optional: Custom URL slug"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["SRHR", "Education", "Teen Pregnancy", "Child Marriage", "GBV", "Emergency Areas", "Legal Frameworks", "West Africa"]
        required: true
      - {label: "Reading Time (e.g., 8 min read)", name: "read_time", widget: "string", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false, hint: "Short summary for previews"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
